sdk-catalogue:
  image: registry.sonata-nfv.eu:5000/sdk-catalogue
  links:
   - mongo
  ports:
    - "4012:4011"
  restart: always

sdk-catalogue_doc:
  image: registry.sonata-nfv.eu:5000/sdk-catalogue
  ports:
    - "8809:8808"
  command: [rake,yard]
  command: [yard, server, -B, 0.0.0.0]
  restart: always

mongodata:
  image: mongo:3.0.4
  volumes:
    - /data/db
  command: --break-mongo

mongo:
  image: mongo:3.0.4
  volumes_from:
    - mongodata
  ports:
    - "27018:27017"
  command: --smallfiles --rest
  restart: always

mongoexpress:
  image: mongo-express
  links:
    - mongo:mongo
  ports:
    - "8082:8081"
  restart: always

