##
## Copyright 2015-2017 i2CAT Foundation
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

source 'https://rubygems.org'

gem 'sinatra', '~>1.4'
gem 'thin', '~>1.6'
gem 'json', '~>1.8'
gem 'sinatra-contrib', '~>1.4'
gem 'nokogiri', '~>1.6'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
#gem 'rubysl-securerandom', '~> 2.0'

group :development, :test do
	gem 'rerun'
	gem 'rspec'
	gem 'rack-test'
	gem 'database_cleaner'
	gem 'factory_girl'
	gem 'rubocop'
	gem 'rubocop-checkstyle_formatter', require: false
end

group :doc do
	gem 'yard', '~>0.8'
end

# Database
gem 'mongoid', '~>4.0' # MongoDB driver
gem 'mongoid-pagination', '~>0.2' # Pagination library
#gem 'mongoid-versioning', '~>1.2' # Versioning library

# Gatekeeper auth gem
#gem 'sinatra-gkauth', '~>0.2.0', path: '../sinatra-gkauth-gem' # <- Disabled