##
## Copyright (c) 2015 SONATA-NFV, i2CAT Foundation
## ALL RIGHTS RESERVED.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##     http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
## Neither the name of the SONATA-NFV, i2CAT Foundation
## nor the names of its contributors may be used to endorse or promote
## products derived from this software without specific prior written
## permission.
##
## This work has been performed in the framework of the SONATA project,
## funded by the European Commission under Grant number 671517 through
## the Horizon 2020 and 5G-PPP programmes. The authors would like to
## acknowledge the contributions of their colleagues of the SONATA
## partner consortium (www.sonata-nfv.eu).

source 'https://rubygems.org'

# gem 'sinatra', '~>1.4'
gem 'puma', '~>3.4.0'
#gem 'thin', '~>1.6'
gem 'json', '~>1.8'
gem 'sinatra', '~> 1.4.3', require: 'sinatra/base'
gem 'sinatra-contrib', '~>1.4', require: false
gem 'rake', '~>11.2.2'
# gem 'nokogiri', '~>1.6'
gem 'json-schema', '~>2.5'
gem 'rest-client', '~>1.8'
#gem 'rubysl-securerandom', '~> 2.0'
gem 'ci_reporter_rspec', '~>1.0.0'

group :development, :test do
  gem 'webmock', '~>2.1.0'
	# gem 'rerun'
  gem 'rspec', '~>3.5.0'
  gem 'rspec-mocks', '~>3.5.0'
  gem 'rack-test', '~>0.6', require: 'rack/test'
  gem 'rspec-its', '~>1.2'
	# gem 'database_cleaner'
	# gem 'factory_girl'
	gem 'rubocop', '~>0.41.2'
	gem 'rubocop-checkstyle_formatter', '~>0.2', require: false
  gem 'license_finder', '~>2.1.2'
end

group :doc do
	gem 'yard', '~>0.8'
end

# Database
gem 'mongoid', '~>4.0' # MongoDB driver
gem 'mongoid-pagination', '~>0.2' # Pagination library
#gem 'mongoid-versioning', '~>1.2' # Versioning library

# Gatekeeper auth gem
#gem 'sinatra-gkauth', '~>0.2.0', path: '../sinatra-gkauth-gem' # <- Disabled
