##
## Copyright 2015-2017 i2CAT Foundation
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
## You may obtain a copy of the License at
##
##   http://www.apache.org/licenses/LICENSE-2.0
##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.

require 'yard'
require 'yaml'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :specs do |task|
	task.pattern = Dir['spec/*_spec.rb']
end

task :default => ['specs']

desc 'Start the service'
task :start do
  puts 'SON-CATALOGUE STARTING...'
	conf = File.expand_path('config.ru', File.dirname(__FILE__))
	conf2 = File.expand_path('config/config.yml', File.dirname(__FILE__))
	exec("thin -C #{conf2} -R #{conf} --debug start")
end

YARD::Rake::YardocTask.new do |t|
	t.files = %w(main.rb helpers/catalogue_helpers.rb routes/catalogue_routes.rb)
end

namespace :db do
	task :load_config do
		require './main'
	end
end